export enum KYCCATEGORY {
  DKYC = "DKYC",
  ADKYC = "ADKYC",
  AAPKYC = "AAPKYC",
  AUPKYC = "AUPKYC",
  RBKYC = "RBKYC",
  BKYC = "BKYC",
  GBKYC = "GBKYC",
  GKYC = "GKYC",
  PBKYC = "PBKYC",
  BLKYC = "BLKYC",
  LKYC = "LKYC",
  PKYC = "PKYC",
  APIKYC = "APIKYC",
  GVTKYC = "GVTKYC",
  SKYC = "SKYC",
  BULKKYC = "BULKKYC",
  NKYC = "NKYC",
  APIUKYC = "APIUKYC",
}

export type ViewInfo = {
  key: string
  label: string
}

export enum KYCSTATUS {
  AGENT_RECEIVED = "AGENT_RECEIVED",
  DSO_COLLECTED = "DSO_COLLECTED",
  DH_COLLECTED = "DH_COLLECTED",
  DH_ACCEPTED = "DH_ACCEPTED",
  DH_REJECTED = "DH_REJECTED",
  IN_TRANSIT = "IN_TRANSIT",
  CS_RECEIVED = "CS_RECEIVED",
  DATA_ENTRY_COMPLETED = "DATA_ENTRY_COMPLETED",
  CS_ACCEPTED = "CS_ACCEPTED",
  SPECIAL_CS_ACCEPTED = "SPECIAL_CS_ACCEPTED",
  CS_DOCUMENT_PENDING = "CS_DOCUMENT_PENDING",
  CS_REJECTED = "CS_REJECTED",
  BO_RECEIVED = "BO_RECEIVED",
  BO_ACCEPTED = "BO_ACCEPTED",
  BO_REJECTED = "BO_REJECTED",
}

export enum KYCSUBSTATUS {
  CS_RECEIVED = "CS_RECEIVED",
  CS_RECEIVED_BIOMETRIC_FAIL = "CS_RECEIVED_BIOMETRIC_FAIL",
  CS_REJECTED = "CS_REJECTED",
  AUTO_APPROVED = "AUTO_APPROVED",
  CS_ACCEPTED = "CS_ACCEPTED",
  SPECIAL_CS_ACCEPTED = "SPECIAL_CS_ACCEPTED",
  AGENT_RECEIVED = "AGENT_RECEIVED",
  DSO_COLLECTED = "DSO_COLLECTED",
  DH_COLLECTED = "DH_COLLECTED",
  DH_ACCEPTED = "DH_ACCEPTED",
  DH_REJECTED = "DH_REJECTED",
  IN_TRANSIT = "IN_TRANSIT",
  DATA_ENTRY_COMPLETED = "DATA_ENTRY_COMPLETED",
  CS_DOCUMENT_PENDING = "CS_DOCUMENT_PENDING",
  BO_PENDING = "BO_PENDING",
  BO_APPROVED = "BO_APPROVED",
  BO_ACCEPTED = "BO_ACCEPTED",
  DELETED = "DELETED",
}

export enum KYCCONDITION {
  INACTIVE = "INACTIVE",
  ACTIVE = "ACTIVE",
}
