/* eslint-disable @typescript-eslint/no-unused-vars */
// import {
//   TListRealizationPendingDataResponse,
//   TListRealizationHistoryDataResponse,
//   TListDigitalCoreWalletResponse,
//   TListDigitalCoreWalletCategoryResponse,
// } from "./payloadAndResponseTypes"

const coreDigitalWalletDummyData: {
  // walletWiseWalletPendingData: TListRealizationPendingDataResponse
  // categoryWiseWalletPendingData: TListRealizationPendingDataResponse
  // walletWiseHistoryData: TListRealizationHistoryDataResponse
  // categorytWiseHistoryData: TListRealizationHistoryDataResponse
  // walletWiseWallets: TListDigitalCoreWalletResponse
  // categoryWiseWallets: TListDigitalCoreWalletCategoryResponse
  walletWiseWalletPendingData: any
  categoryWiseWalletPendingData: any
  walletWiseHistoryData: any
  categorytWiseHistoryData: any
  walletWiseWallets: any
  categoryWiseWallets: any
} = {
  walletWiseWalletPendingData: {
    status: "SUCCESS",
    message: "success",
    responseCode: 20000,
    data: {
      totalPendingRealization: 25,
      totalAmount: 50000,
      records: [
        {
          walletTxnSummaryId: "12312",
          walletId: "1012865",
          walletName: "walletName",
          transactionDate: new Date("02-25-2023").getTime(),
          transactionCount: 34,
          amount: 54.5,
        },
        {
          walletTxnSummaryId: "12312",
          walletId: "1012865",
          walletName: "walletName",
          transactionDate: new Date("02-25-2023").getTime(),
          transactionCount: 34,
          amount: 54.5,
        },
        {
          walletTxnSummaryId: "12312",
          walletId: "1012865",
          walletName: "walletName",
          transactionDate: new Date("02-25-2023").getTime(),
          transactionCount: 34,
          amount: 54.5,
        },
        {
          walletTxnSummaryId: "12312",
          walletId: "1012865",
          walletName: "walletName",
          transactionDate: new Date("02-25-2023").getTime(),
          transactionCount: 34,
          amount: 54.5,
        },
        {
          walletTxnSummaryId: "12312",
          walletId: "1012865",
          walletName: "walletName",
          transactionDate: new Date("02-25-2023").getTime(),
          transactionCount: 34,
          amount: 54.5,
        },
      ],
    },
    pagination: {
      page: 0,
      perPage: 10,
      totalRecords: 10,
      totalPages: 1,
    },
  },
  categoryWiseWalletPendingData: {
    status: "SUCCESS",
    message: "success",
    responseCode: 20000,
    data: {
      totalPendingRealization: 25,
      totalAmount: 50000,
      records: [
        {
          walletTxnSummaryId: "12312",
          walletId: "1012865",
          walletName: "walletName",
          transactionDate: new Date("02-25-2023").getTime(),
          transactionCount: 34,
          amount: 54.5,
        },
        {
          walletTxnSummaryId: "12312",
          walletId: "1012865",
          walletName: "walletName",
          transactionDate: new Date("02-25-2023").getTime(),
          transactionCount: 34,
          amount: 54.5,
        },
        {
          walletTxnSummaryId: "12312",
          walletId: "1012865",
          walletName: "walletName",
          transactionDate: new Date("02-25-2023").getTime(),
          transactionCount: 34,
          amount: 54.5,
        },
        {
          walletTxnSummaryId: "12312",
          walletId: "1012865",
          walletName: "walletName",
          transactionDate: new Date("02-25-2023").getTime(),
          transactionCount: 34,
          amount: 54.5,
        },
        {
          walletTxnSummaryId: "12312",
          walletId: "1012865",
          walletName: "walletName",
          transactionDate: new Date("02-25-2023").getTime(),
          transactionCount: 34,
          amount: 54.5,
        },
      ],
    },
    pagination: {
      page: 0,
      perPage: 10,
      totalRecords: 10,
      totalPages: 1,
    },
  },
  walletWiseHistoryData: {
    status: "SUCCESS",
    message: "success",
    responseCode: 20000,
    data: {
      totalAmount: 50000,
      records: [
        {
          realizationTxnId: "<Trxn Id>",
          walletTrxnSummaryId: "Summary",
          walletId: "X1W2DF34TY",
          creationDate: new Date("02-25-2023").getTime(),
          realizationDate: new Date("02-25-2023").getTime(),
          transactionDate: new Date("02-25-2023").getTime(),
          transactionCount: 12,
          totalAmount: 1000,
          tcsaBankAccount: "<TCSA Bank_name-Account>",
          operationBankAccount: "<Operational Bank_name-Account>",
          requestedBy: "Amit Das",
          requestedUserCode: "ADas",
          requstedUserRemarks: "Test",
          approvalStatus: "Approved",
          approvedBy: "ADas",
          amsConfigCode: "CODE",
          requestCategory: "Realization",
          moduleName: "Fund Realization",
          approvalCode: "CODE12",
          requestCode: "Code",
          lastUpdationDate: new Date("02-25-2023").getTime(),
          currentApproverUserType: "BO User",
          currentApproverUserLevel: "L1",
          currentApproverUserCode: "ADas",
          nextApproverUserLevel: "L2",
        },
        {
          realizationTxnId: "<Trxn Id>",
          walletTrxnSummaryId: "Summary",
          walletId: "X1W2DF34TY",
          creationDate: new Date("02-25-2023").getTime(),
          realizationDate: new Date("02-25-2023").getTime(),
          transactionDate: new Date("02-25-2023").getTime(),
          transactionCount: 12,
          totalAmount: 1000,
          tcsaBankAccount: "<TCSA Bank_name-Account>",
          operationBankAccount: "<Operational Bank_name-Account>",
          requestedBy: "Amit Das",
          requestedUserCode: "ADas",
          requstedUserRemarks: "Test",
          approvalStatus: "Approved",
          approvedBy: "ADas",
          amsConfigCode: "CODE",
          requestCategory: "Realization",
          moduleName: "Fund Realization",
          approvalCode: "CODE12",
          requestCode: "Code",
          lastUpdationDate: new Date("02-25-2023").getTime(),
          currentApproverUserType: "BO User",
          currentApproverUserLevel: "L1",
          currentApproverUserCode: "ADas",
          nextApproverUserLevel: "L2",
        },
        {
          realizationTxnId: "<Trxn Id>",
          walletTrxnSummaryId: "Summary",
          walletId: "X1W2DF34TY",
          creationDate: new Date("02-25-2023").getTime(),
          realizationDate: new Date("02-25-2023").getTime(),
          transactionDate: new Date("02-25-2023").getTime(),
          transactionCount: 12,
          totalAmount: 1000,
          tcsaBankAccount: "<TCSA Bank_name-Account>",
          operationBankAccount: "<Operational Bank_name-Account>",
          requestedBy: "Amit Das",
          requestedUserCode: "ADas",
          requstedUserRemarks: "Test",
          approvalStatus: "Approved",
          approvedBy: "ADas",
          amsConfigCode: "CODE",
          requestCategory: "Realization",
          moduleName: "Fund Realization",
          approvalCode: "CODE12",
          requestCode: "Code",
          lastUpdationDate: new Date("02-25-2023").getTime(),
          currentApproverUserType: "BO User",
          currentApproverUserLevel: "L1",
          currentApproverUserCode: "ADas",
          nextApproverUserLevel: "L2",
        },
        {
          realizationTxnId: "<Trxn Id>",
          walletTrxnSummaryId: "Summary",
          walletId: "X1W2DF34TY",
          creationDate: new Date("02-25-2023").getTime(),
          realizationDate: new Date("02-25-2023").getTime(),
          transactionDate: new Date("02-25-2023").getTime(),
          transactionCount: 12,
          totalAmount: 1000,
          tcsaBankAccount: "<TCSA Bank_name-Account>",
          operationBankAccount: "<Operational Bank_name-Account>",
          requestedBy: "Amit Das",
          requestedUserCode: "ADas",
          requstedUserRemarks: "Test",
          approvalStatus: "Approved",
          approvedBy: "ADas",
          amsConfigCode: "CODE",
          requestCategory: "Realization",
          moduleName: "Fund Realization",
          approvalCode: "CODE12",
          requestCode: "Code",
          lastUpdationDate: new Date("02-25-2023").getTime(),
          currentApproverUserType: "BO User",
          currentApproverUserLevel: "L1",
          currentApproverUserCode: "ADas",
          nextApproverUserLevel: "L2",
        },
        {
          realizationTxnId: "<Trxn Id>",
          walletTrxnSummaryId: "Summary",
          walletId: "X1W2DF34TY",
          creationDate: new Date("02-25-2023").getTime(),
          realizationDate: new Date("02-25-2023").getTime(),
          transactionDate: new Date("02-25-2023").getTime(),
          transactionCount: 12,
          totalAmount: 1000,
          tcsaBankAccount: "<TCSA Bank_name-Account>",
          operationBankAccount: "<Operational Bank_name-Account>",
          requestedBy: "Amit Das",
          requestedUserCode: "ADas",
          requstedUserRemarks: "Test",
          approvalStatus: "Approved",
          approvedBy: "ADas",
          amsConfigCode: "CODE",
          requestCategory: "Realization",
          moduleName: "Fund Realization",
          approvalCode: "CODE12",
          requestCode: "Code",
          lastUpdationDate: new Date("02-25-2023").getTime(),
          currentApproverUserType: "BO User",
          currentApproverUserLevel: "L1",
          currentApproverUserCode: "ADas",
          nextApproverUserLevel: "L2",
        },
      ],
    },
    pagination: {
      page: 0,
      perPage: 10,
      totalRecords: 10,
      totalPages: 1,
    },
  },
  categorytWiseHistoryData: {
    status: "SUCCESS",
    message: "success",
    responseCode: 20000,
    data: {
      totalAmount: 50000,
      records: [
        {
          realizationTxnId: "<Trxn Id>",
          walletTrxnSummaryId: "Summary",
          walletId: "X1W2DF34TY",
          creationDate: new Date("02-25-2023").getTime(),
          realizationDate: new Date("02-25-2023").getTime(),
          transactionDate: new Date("02-25-2023").getTime(),
          transactionCount: 12,
          totalAmount: 1000,
          tcsaBankAccount: "<TCSA Bank_name-Account>",
          operationBankAccount: "<Operational Bank_name-Account>",
          requestedBy: "Amit Das",
          requestedUserCode: "ADas",
          requstedUserRemarks: "Test",
          approvalStatus: "Approved",
          approvedBy: "ADas",
          amsConfigCode: "CODE",
          requestCategory: "Realization",
          moduleName: "Fund Realization",
          approvalCode: "CODE12",
          requestCode: "Code",
          lastUpdationDate: new Date("02-25-2023").getTime(),
          currentApproverUserType: "BO User",
          currentApproverUserLevel: "L1",
          currentApproverUserCode: "ADas",
          nextApproverUserLevel: "L2",
        },
        {
          realizationTxnId: "<Trxn Id>",
          walletTrxnSummaryId: "Summary",
          walletId: "X1W2DF34TY",
          creationDate: new Date("02-25-2023").getTime(),
          realizationDate: new Date("02-25-2023").getTime(),
          transactionDate: new Date("02-25-2023").getTime(),
          transactionCount: 12,
          totalAmount: 1000,
          tcsaBankAccount: "<TCSA Bank_name-Account>",
          operationBankAccount: "<Operational Bank_name-Account>",
          requestedBy: "Amit Das",
          requestedUserCode: "ADas",
          requstedUserRemarks: "Test",
          approvalStatus: "Approved",
          approvedBy: "ADas",
          amsConfigCode: "CODE",
          requestCategory: "Realization",
          moduleName: "Fund Realization",
          approvalCode: "CODE12",
          requestCode: "Code",
          lastUpdationDate: new Date("02-25-2023").getTime(),
          currentApproverUserType: "BO User",
          currentApproverUserLevel: "L1",
          currentApproverUserCode: "ADas",
          nextApproverUserLevel: "L2",
        },
        {
          realizationTxnId: "<Trxn Id>",
          walletTrxnSummaryId: "Summary",
          walletId: "X1W2DF34TY",
          creationDate: new Date("02-25-2023").getTime(),
          realizationDate: new Date("02-25-2023").getTime(),
          transactionDate: new Date("02-25-2023").getTime(),
          transactionCount: 12,
          totalAmount: 1000,
          tcsaBankAccount: "<TCSA Bank_name-Account>",
          operationBankAccount: "<Operational Bank_name-Account>",
          requestedBy: "Amit Das",
          requestedUserCode: "ADas",
          requstedUserRemarks: "Test",
          approvalStatus: "Approved",
          approvedBy: "ADas",
          amsConfigCode: "CODE",
          requestCategory: "Realization",
          moduleName: "Fund Realization",
          approvalCode: "CODE12",
          requestCode: "Code",
          lastUpdationDate: new Date("02-25-2023").getTime(),
          currentApproverUserType: "BO User",
          currentApproverUserLevel: "L1",
          currentApproverUserCode: "ADas",
          nextApproverUserLevel: "L2",
        },
        {
          realizationTxnId: "<Trxn Id>",
          walletTrxnSummaryId: "Summary",
          walletId: "X1W2DF34TY",
          creationDate: new Date("02-25-2023").getTime(),
          realizationDate: new Date("02-25-2023").getTime(),
          transactionDate: new Date("02-25-2023").getTime(),
          transactionCount: 12,
          totalAmount: 1000,
          tcsaBankAccount: "<TCSA Bank_name-Account>",
          operationBankAccount: "<Operational Bank_name-Account>",
          requestedBy: "Amit Das",
          requestedUserCode: "ADas",
          requstedUserRemarks: "Test",
          approvalStatus: "Approved",
          approvedBy: "ADas",
          amsConfigCode: "CODE",
          requestCategory: "Realization",
          moduleName: "Fund Realization",
          approvalCode: "CODE12",
          requestCode: "Code",
          lastUpdationDate: new Date("02-25-2023").getTime(),
          currentApproverUserType: "BO User",
          currentApproverUserLevel: "L1",
          currentApproverUserCode: "ADas",
          nextApproverUserLevel: "L2",
        },
        {
          realizationTxnId: "<Trxn Id>",
          walletTrxnSummaryId: "Summary",
          walletId: "X1W2DF34TY",
          creationDate: new Date("02-25-2023").getTime(),
          realizationDate: new Date("02-25-2023").getTime(),
          transactionDate: new Date("02-25-2023").getTime(),
          transactionCount: 12,
          totalAmount: 1000,
          tcsaBankAccount: "<TCSA Bank_name-Account>",
          operationBankAccount: "<Operational Bank_name-Account>",
          requestedBy: "Amit Das",
          requestedUserCode: "ADas",
          requstedUserRemarks: "Test",
          approvalStatus: "Approved",
          approvedBy: "ADas",
          amsConfigCode: "CODE",
          requestCategory: "Realization",
          moduleName: "Fund Realization",
          approvalCode: "CODE12",
          requestCode: "Code",
          lastUpdationDate: new Date("02-25-2023").getTime(),
          currentApproverUserType: "BO User",
          currentApproverUserLevel: "L1",
          currentApproverUserCode: "ADas",
          nextApproverUserLevel: "L2",
        },
      ],
    },
    pagination: {
      page: 0,
      perPage: 10,
      totalRecords: 10,
      totalPages: 1,
    },
  },
  walletWiseWallets: {
    status: "SUCCESS",
    message: "success",
    responseCode: 20000,
    data: [
      {
        accountName: "",
        accountType: "",
        bankAccountName: "",
        bankAccountNumber: "",
        bankName: "",
        branchName: "",
        control: "",
        glCode: "",
        routingNumber: 0,
        subControl: "",
        subsidiary: "",
        walletCode: "1",
        walletName: "Fee Realization - Regular",
      },
      {
        accountName: "",
        accountType: "",
        bankAccountName: "",
        bankAccountNumber: "",
        bankName: "",
        branchName: "",
        control: "",
        glCode: "",
        routingNumber: 0,
        subControl: "",
        subsidiary: "",
        walletCode: "2",
        walletName: "Fee Realization - Islamic",
      },
      {
        accountName: "",
        accountType: "",
        bankAccountName: "",
        bankAccountNumber: "",
        bankName: "",
        branchName: "",
        control: "",
        glCode: "",
        routingNumber: 0,
        subControl: "",
        subsidiary: "",
        walletCode: "3",
        walletName: "Topup Fee Realization - Regular",
      },
      {
        accountName: "",
        accountType: "",
        bankAccountName: "",
        bankAccountNumber: "",
        bankName: "",
        branchName: "",
        control: "",
        glCode: "",
        routingNumber: 0,
        subControl: "",
        subsidiary: "",
        walletCode: "4",
        walletName: "Topup Fee Realization - Islamic",
      },
      {
        accountName: "",
        accountType: "",
        bankAccountName: "",
        bankAccountNumber: "",
        bankName: "",
        branchName: "",
        control: "",
        glCode: "",
        routingNumber: 0,
        subControl: "",
        subsidiary: "",
        walletCode: "5",
        walletName: "VAT Realization - Regular",
      },
      {
        accountName: "",
        accountType: "",
        bankAccountName: "",
        bankAccountNumber: "",
        bankName: "",
        branchName: "",
        control: "",
        glCode: "",
        routingNumber: 0,
        subControl: "",
        subsidiary: "",
        walletCode: "6",
        walletName: "VAT Realization - Islamic",
      },
      {
        accountName: "",
        accountType: "",
        bankAccountName: "",
        bankAccountNumber: "",
        bankName: "",
        branchName: "",
        control: "",
        glCode: "",
        routingNumber: 0,
        subControl: "",
        subsidiary: "",
        walletCode: "7",
        walletName: "BPO Realization - Regular",
      },
      {
        accountName: "",
        accountType: "",
        bankAccountName: "",
        bankAccountNumber: "",
        bankName: "",
        branchName: "",
        control: "",
        glCode: "",
        routingNumber: 0,
        subControl: "",
        subsidiary: "",
        walletCode: "8",
        walletName: "BPO Realization - Islamic",
      },
      {
        accountName: "",
        accountType: "",
        bankAccountName: "",
        bankAccountNumber: "",
        bankName: "",
        branchName: "",
        control: "",
        glCode: "",
        routingNumber: 0,
        subControl: "",
        subsidiary: "",
        walletCode: "9",
        walletName: "NL Realization - Regular",
      },
      {
        accountName: "",
        accountType: "",
        bankAccountName: "",
        bankAccountNumber: "",
        bankName: "",
        branchName: "",
        control: "",
        glCode: "",
        routingNumber: 0,
        subControl: "",
        subsidiary: "",
        walletCode: "10",
        walletName: "NL Realization - Islamic",
      },
    ],
  },
  categoryWiseWallets: {
    status: "SUCCESS",
    message: "success",
    responseCode: 20000,
    data: [
      {
        categorycode: "1",
        name: "Airtime Realization - Regular",
      },
      {
        categorycode: "2",
        name: "Airtime Realization - Islamic",
      },
      {
        categorycode: "3",
        name: "AIT Realization - Regular",
      },
      {
        categorycode: "4",
        name: "AIT Realization - Islamic",
      },
    ],
  },
}

export default function getCoreDigitalWalletDummyData(
  what: keyof typeof coreDigitalWalletDummyData,
  _payload: any,
) {
  return coreDigitalWalletDummyData[what]
}
